Fix Error loading version latest: Error: Cannot find module 'extend'
This error is due to an issue with the new released version 2.3.1 of
gitbook-cli (https://github.com/GitbookIO/gitbook-cli/issues/68 and
https://github.com/GitbookIO/gitbook/issues/1818)